[tool.poetry]
name = "dataverse-api"
version = "0.1.1"
description = ""
authors = ["Marcus Risanger <69350948+MarcusRisanger@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
msal = "^1.22.0"
msal-requests-auth = "^0.7.0"
pandas = "^2.0.1"
requests-toolbelt = "^1.0.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ipykernel = "^6.22.0"
python-dotenv = "^1.0.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.3.1"
coverage = "^7.2.5"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = 'black'
